export enum AFErrorCode {
  MISSING_ABRA_COMPANY = 'MISSING_ABRA_COMPANY',
  ABRA_FLEXI_ERROR = 'ABRA_FLEXI_ERROR',
  ALREADY_IN_USE = 'ALREADY_IN_USE',
  QUERY_DETAIL_UNKNOWN_KEY = 'QUERY_DETAIL_UNKNOWN_KEY',
  MISSING_ID_IN_POPULATE = 'MISSING_ID_IN_POPULATE',
  OBJECT_NOT_FOUND = 'OBJECT_NOT_FOUND',
  PROPERTY_NOT_FOUND = 'PROPERTY_NOT_FOUND',
  FORBIDDEN_OPERATION = 'FORBIDDEN_OPERATION',
  NEW_ENTITY_SERIALIZE_ID_ATTEMPT = 'NEW_ENTITY_SERIALIZE_ID_ATTEMPT',
  UNDEFINED_CANT_BE_SERIALIZED = 'UNDEFINED_CANT_BE_SERIALIZED',
  RELATED_INSTANCE_NOT_SAVED = 'RELATED_INSTANCE_NOT_SAVED',
  UNKNOWN_PROPERTY_TYPE = 'UNKNOWN_PROPERTY_TYPE',
  ENUM_TYPE_MISSING = 'ENUM_TYPE_MISSING',
  ITEM_TYPE_MISSING = 'ITEM_TYPE_MISSING',
  
  // Session errors
  LOGIN_UNDERWAY = 'LOGIN_UNDERWAY',
  LOGIN_FAILED = 'LOGIN_FAILED',
  LOGOUT_UNDERWAY = 'LOGOUT_UNDERWAY',
  SESSION_NOT_ONLINE = 'SESSION_NOT_ONLINE',
  PASSWORD_EMPTY = 'PASSWORD_EMPTY',
  
  UNKNOWN = 'UNKNOWN'
}

export class AFError extends Error {
  get code(): AFErrorCode {
    return this.name as AFErrorCode
  }

  constructor(code: AFErrorCode, msg?: string) {
    super(`[AFError].${code}: ${msg}`)
    this.name = code
  }
}