/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AbraDetail: typeof import('./src/components/AbraDetail.vue')['default']
    AddTab: typeof import('./src/components/AddTab.vue')['default']
    AgendaDetail: typeof import('./src/components/AgendaDetail.vue')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    Tabs: typeof import('primevue/tabs')['default']
  }
}
