/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AbraDetail: typeof import('./src/components/AbraDetail.vue')['default']
    AddTab: typeof import('./src/components/AddTab.vue')['default']
    AgendaDetail: typeof import('./src/components/AgendaDetail.vue')['default']
    Button: typeof import('primevue/button')['default']
    Column: typeof import('primevue/column')['default']
    Connection: typeof import('./src/components/Connection.vue')['default']
    ConnectionDetail: typeof import('./src/components/ConnectionDetail.vue')['default']
    ConnectionForm: typeof import('./src/components/ConnectionForm.vue')['default']
    ConnectionList: typeof import('./src/components/ConnectionList.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    EntityBrowser: typeof import('./src/components/EntityBrowser.vue')['default']
    EntityDetail: typeof import('./src/components/EntityDetail.vue')['default']
    EntityPicker: typeof import('./src/components/EntityPicker.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    IconPicker: typeof import('./src/components/IconPicker.vue')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menu: typeof import('primevue/menu')['default']
    Message: typeof import('primevue/message')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    PanelMenu: typeof import('primevue/panelmenu')['default']
    Password: typeof import('primevue/password')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Tag: typeof import('primevue/tag')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
